kind: Service
apiVersion: v1
metadata:
  name: iotmlwebapp
  labels:
    app: iotmlwebapp
spec:
  selector:
    run: iotmlwebapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iotmlwebapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: iotmlwebapp
        app: iotmlwebapp
    spec:
      containers:
      - name: iotmlwebapp
        image: iotml.azurecr.io/iotmlwebapp
        env:
        - name: HOST_PLATFORM
          value: "ACS Kubernetes"
        - name: BACK_COLOR
          value: "green"
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regsecret